cloudfront

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -361,15 +361,15 @@ jobs:
             if curl -s ${URL} | grep "Welcome"
             then
                 # Change this to 0 after the job fails
-              return 1
+              return 0
             else
               return 1
             fi
       # Here's where you will add some code to rollback on failure
-      - destroy-environment:
-          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
-      - revert-migrations:
-          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7} 
+      # - destroy-environment:
+      #     workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
+      # - revert-migrations:
+      #     workflow_id: ${CIRCLE_WORKFLOW_ID:0:7} 
 
 
   cloudfront-update:
@@ -414,44 +414,44 @@ jobs:
       # - revert-migrations:
       #     workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}  
 
-cleanup:
-    docker:
-      # Docker image here
-      - image: amazon/aws-cli 
-    steps:
-      # Checkout code from git
-      - checkout
+# cleanup:
+#     docker:
+#       # Docker image here
+#       - image: amazon/aws-cli 
+#     steps:
+#       # Checkout code from git
+#       - checkout
 
-      - run:
-          name: Install dependencies
-          command: |
-            yum install tar gzip -y
-      - attach_workspace:
-          at: ~/
-      - run:
-          name: Get old stack workflow id
-          command: |
-            # your code here
-            export STACKS=($(aws cloudfromation list-stacks --query "StacksSummaries[*].StackName" \
-              --stack-status-filter CREATE_COMPLETE --no-paginate --output text))
-            echo Stack names: "${STACKS[@]}"
-            cat ~/project/OldWorkflowID.txt
-            export OldWorkflowID=$(cat ~/project/OldWorkflowID.txt)
-            echo OldWorkflowID: "${OldWorkflowID}"
-      - run:
-          name: Remove old stacks and files
-          command: |
-            export OldWorkflowID=$(cat ~/project/OldWorkflowID.txt)
-            if [[ "${CIRCLE_WORKFLOW_ID:0:7}" != "${OldWorkflowID}" ]]
-            then
-              echo "Deleting Old Stack"
-              echo "s3://udapeople-${OldWorkflowID}"
-              aws s3 rm "s3://udapeople-${OldWorkflowID}" --recursive || true
-              aws cloudformation delete-stack --stack-name "udapeople-backend-${OldWorkflowID}" || true
-              aws cloudformation delete-stack --stack-name "udapeople-frontend-${OldWorkflowID}" || true
-            else
-              echo "Stack is the latest"
-            fi
+#       - run:
+#           name: Install dependencies
+#           command: |
+#             yum install tar gzip -y
+#       - attach_workspace:
+#           at: ~/
+#       - run:
+#           name: Get old stack workflow id
+#           command: |
+#             # your code here
+#             export STACKS=($(aws cloudfromation list-stacks --query "StacksSummaries[*].StackName" \
+#               --stack-status-filter CREATE_COMPLETE --no-paginate --output text))
+#             echo Stack names: "${STACKS[@]}"
+#             cat ~/project/OldWorkflowID.txt
+#             export OldWorkflowID=$(cat ~/project/OldWorkflowID.txt)
+#             echo OldWorkflowID: "${OldWorkflowID}"
+#       - run:
+#           name: Remove old stacks and files
+#           command: |
+#             export OldWorkflowID=$(cat ~/project/OldWorkflowID.txt)
+#             if [[ "${CIRCLE_WORKFLOW_ID:0:7}" != "${OldWorkflowID}" ]]
+#             then
+#               echo "Deleting Old Stack"
+#               echo "s3://udapeople-${OldWorkflowID}"
+#               aws s3 rm "s3://udapeople-${OldWorkflowID}" --recursive || true
+#               aws cloudformation delete-stack --stack-name "udapeople-backend-${OldWorkflowID}" || true
+#               aws cloudformation delete-stack --stack-name "udapeople-frontend-${OldWorkflowID}" || true
+#             else
+#               echo "Stack is the latest"
+#             fi
             
 
 workflows:
@@ -484,5 +484,5 @@ workflows:
           requires: [deploy-backend, deploy-frontend]
       - cloudfront-update:
           requires: [smoke-test]
-      - cleanup:
-          requires: [cloudfront-update]
+      # - cleanup:
+      #     requires: [cloudfront-update]
